### PR TITLE
Added screenshots for appdata

### PR DESCRIPTION
**Pull request by Ablu**
The existing screenshots are unfortunatly not of an usable ratio.

### CODE REVIEW

**Comment by Ablu** [comment]
If you have better screenshots in a format like described here: http://people.freedesktop.org/~hughsient/appdata/ Feel free to provide those :)

**Comment by bjorn** [comment]
Erm, these screenshots need to be hosted on the website?

**Comment by Ablu** [comment]
Well at least hosted somewhere available for download.

**Comment by bjorn** [comment]
Alright.

**Pull request merged**
